apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../app
components:
  # works: replace while name is still "storefront", then rename
  - ../../components/security
  - ../../components/prefix
